# Generated by Django 5.2.8 on 2025-11-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['fullname'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
