# Generated by Django 5.2.8 on 2025-11-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('groups', '0004_alter_group_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='groups.group'),
        ),
    ]
