# Generated by Django 5.2.8 on 2025-11-23 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_feedback_message_feedback_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='lesson_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
