# Generated by Django 5.2.8 on 2025-11-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_feedback_lesson_date_feedback_lesson_time'),
        ('students', '0002_alter_student_options_rename_name_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['student', '-number'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='group',
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='students.student'),
        ),
    ]
