# Generated by Django 5.2.8 on 2025-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_alter_feedback_options_remove_feedback_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='activity_score',
            field=models.CharField(choices=[(0, 'Tidak Aktif'), (1, 'Kurang Aktif'), (2, 'Cukup Aktif'), (3, 'Aktif')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='attendance_score',
            field=models.CharField(choices=[(0, 'Tidak Hadir'), (1, 'Hadir 1x Sebulan'), (2, 'Hadir 2x Sebulan'), (3, 'Hadir 3x Sebulan'), (4, 'Selalu Hadir')], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task_score',
            field=models.CharField(choices=[(0, 'Tidak Mengerjakan Tugas'), (1, 'Mengerjakan Sebgian Tugas'), (2, 'Mengerjakan Semua')], default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='url_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
