# Generated by Django 5.2.8 on 2025-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_feedback_activity_score_feedback_attendance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
