# Generated by Django 5.2.8 on 2025-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_feedback_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
