# Generated by Django 5.2.8 on 2025-11-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0008_feedback_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='task_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
