# Generated by Django 5.2.8 on 2025-11-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
