# Generated by Django 5.2.8 on 2025-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10),
        ),
    ]
