# Generated by Django 5.2.8 on 2025-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lesson_count',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_time',
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Group', 'Group'), ('Private', 'Private')], default='Group', max_length=10),
        ),
    ]
