# Generated by Django 5.2.8 on 2025-11-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_capacity_remove_group_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
