# Generated by Django 5.2.8 on 2025-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
