# Generated by Django 5.2.8 on 2025-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_group_phone_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='first_lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='first_lesson_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
