# Generated by Django 5.2.8 on 2025-11-16 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_start',
            field=models.DateField(default=datetime.date(2025, 11, 16)),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(default='09:11:56'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.CharField(max_length=20),
        ),
    ]
