# Generated by Django 5.2.8 on 2025-11-16 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_end_time_remove_lesson_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(default='09:12:29'),
        ),
    ]
