# Generated by Django 5.2.8 on 2025-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_date_start_alter_lesson_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(default='09:18:41'),
        ),
    ]
