# Generated by Django 5.2.8 on 2025-11-16 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
