# Generated by Django 5.2.8 on 2025-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_time_start'),
        ('students', '0002_alter_student_options_rename_name_student_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='students_attended',
            field=models.ManyToManyField(blank=True, related_name='attended_lessons', to='students.student'),
        ),
    ]
