# Generated by Django 5.2.8 on 2025-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_level_alter_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
