# Generated by Django 5.2.8 on 2025-11-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lesson_meeting_link_alter_lesson_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['number', 'group__name'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
