# Generated by Django 5.2.8 on 2025-11-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['group__name', 'number'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
