# Generated by Django 5.2.8 on 2025-12-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
